//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RGZ
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KRBDEntities : DbContext
    {
        private static KRBDEntities _context;
        public KRBDEntities()
            : base("name=KRBDEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public static KRBDEntities GetContext()
        {
            if (_context == null)
                _context = new KRBDEntities();
            return _context;
        }

        public DbSet<Buyer> Buyer { get; set; }
        public DbSet<Passport> Passport { get; set; }
        public DbSet<State> State { get; set; }
    }
}
