//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RGZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passport
    {
        public Passport()
        {
            this.Buyer = new HashSet<Buyer>();
        }
    
        public int PassportID { get; set; }
        public int Serial { get; set; }
        public int Number { get; set; }
        public System.DateTime DateOfIssue { get; set; }
        public string IssuedByWhom { get; set; }
    
        public virtual ICollection<Buyer> Buyer { get; set; }
    }
}
